$DISBLAE_FIREWALL = <<-SCRIPT
    sudo systemctl disable firewalld --now
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.provision "shell", inline: $DISBLAE_FIREWALL
    config.vm.define "worker1" do |worker|
        worker.vm.hostname = "worker1"
        worker.vm.network "public_network", ip: "192.168.42.111",  bridge: "en0: Ethernet"
        # worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/key.pub"
        # master.vm.synced_folder "./shared", "/vagrant_shared"
        worker.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--name", "worker1"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            # vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
        end
        worker.vm.provision "shell", path: "worker.sh"
    end
end
