$DISBLAE_FIREWALL = <<-SCRIPT
    sudo systemctl disable firewalld --now
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.provision "shell", inline: $DISBLAE_FIREWALL
    config.vm.define "master" do |master|
        master.vm.hostname = "master"
        master.vm.network "public_network", ip: "192.168.42.110", bridge: "en0: Ethernet"
        # master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/key.pub"
        # master.vm.synced_folder "./shared", "/vagrant_shared"
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--name", "master"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            # vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
        end
        master.vm.provision "shell", path: "master.sh", args: ["192.168.42.110"]
    end
end
